spring:
  application:
    name: core

  # Datasource (обязательно для JPA/Liquibase)
  datasource:
    url: jdbc:h2:mem:core;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  # JPA / Hibernate (схема управляется Liquibase)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-status-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Сервер
server:
  port: 8082
  servlet:
    context-path: /

# API-клиенты для аутентификации (client-id -> api-token)
security:
  clients:
    demo-client: demo-token
    credit-service: client-client-api-token
    # client-id: api-token

# Топик событий статуса пользователя
user-status:
  topic: user-status
